### ISSUE TITLE
Sponsor mosaic

### ISSUE THREAD

**Issue by j4kim** [j4kim/fcb#14]
Options :

1. Créer une page standard qui est filtrée des autres en frontend. Option la plus simple s'il est possible de créer facilement une mosaïque dans l'éditeur (ou alors installer un plugin de mosaïque).
2. Ajouter les images dans la bibliothèque et préfixer leur nom par `sponsor`. Récupérer ces images depuis une requête ajax sur `/media`. Option élégante mais problématique pour les sponsors qui n'ont pas d'image.
3. Développer un plugin WordPress
    3.1. Qui enregistre des options en base de données
    3.2. Qui fournit un type de post personnalisé
4. Utiliser une autre API
    4.1. Fichier JSON
    4.2. Mini programme PHP à développer
    4.3. Google Sheets

**Comment by j4kim** [comment]
Plugin `sponsors-mosaic` créé. Il déclare un type de post personnalisé "sponsors".

Il faut créer un post par sponsor, copier coller les infos et ajouter l'image en taille minimale.
Ca marche bien mais ça va être super long... 

Après réflexion, peut-être que l'idée de Google Sheets est meilleure.
Le tableur sur sheets contiendrait Raison sociale, adresse, tel, couleur de fond, taille de la tuile et nom de l'image.
La gestion serait décentralisée mais la mise en place beaucoup plus rapide.

**Comment by j4kim** [comment]
Plutôt qu'avoir le chemin du fichier dans la sheet, on pourrait avoir le nom du media et faire le lien avec les medias wordpress en faisant une requête sur l'api rest /media

**Comment by j4kim** [comment]
Ou alors appeler le media comme la raison sociale dans sheets

**Comment by j4kim** [comment]
Pour afficher des sponsors plus grands:
```css
.grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
  grid-gap: 1rem;
}
.double {
  grid-area: span 1 / span 2;
}
.quad {
  grid-area: span 2 / span 2;
}
```
